[2025-03-26T22:10:29.719+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_store_dag.run_fetch_store_script manual__2025-03-26T22:08:23.379304+00:00 [queued]>
[2025-03-26T22:10:29.723+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_store_dag.run_fetch_store_script manual__2025-03-26T22:08:23.379304+00:00 [queued]>
[2025-03-26T22:10:29.724+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2025-03-26T22:10:29.737+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): run_fetch_store_script> on 2025-03-26 22:08:23.379304+00:00
[2025-03-26T22:10:29.741+0000] {standard_task_runner.py:57} INFO - Started process 68633 to run task
[2025-03-26T22:10:29.744+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_store_dag', 'run_fetch_store_script', 'manual__2025-03-26T22:08:23.379304+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/fetch_store_dag.py', '--cfg-path', '/tmp/tmpoxj2paf2']
[2025-03-26T22:10:29.745+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask run_fetch_store_script
[2025-03-26T22:10:29.771+0000] {task_command.py:410} INFO - Running <TaskInstance: fetch_store_dag.run_fetch_store_script manual__2025-03-26T22:08:23.379304+00:00 [running]> on host codespaces-d2646d
[2025-03-26T22:10:29.814+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_store_dag' AIRFLOW_CTX_TASK_ID='run_fetch_store_script' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T22:08:23.379304+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-26T22:08:23.379304+00:00'
[2025-03-26T22:10:29.815+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-03-26T22:10:29.815+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/home/vscode/miniconda/envs/airflow-env/bin/python /workspaces/Team-34/src/data/fetch_store.py']
[2025-03-26T22:10:29.824+0000] {subprocess.py:86} INFO - Output:
[2025-03-26T22:10:30.189+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-03-26T22:10:30.190+0000] {subprocess.py:93} INFO -   File "/workspaces/Team-34/src/data/fetch_store.py", line 10, in <module>
[2025-03-26T22:10:30.190+0000] {subprocess.py:93} INFO -     import schedule
[2025-03-26T22:10:30.190+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'schedule'
[2025-03-26T22:10:30.237+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-26T22:10:30.244+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/miniconda/envs/airflow-env/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-26T22:10:30.248+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=fetch_store_dag, task_id=run_fetch_store_script, execution_date=20250326T220823, start_date=20250326T221029, end_date=20250326T221030
[2025-03-26T22:10:30.266+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task run_fetch_store_script (Bash command failed. The command returned a non-zero exit code 1.; 68633)
[2025-03-26T22:10:30.278+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-03-26T22:10:30.304+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
